"""Table api request, colum status,url

Revision ID: 25d4d4b5518c
Revises: 7464aa741f57
Create Date: 2024-12-12 21:02:10.607076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d4d4b5518c'
down_revision = '7464aa741f57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_requests', sa.Column('status', sa.String(length=250), nullable=True))
    op.add_column('api_requests', sa.Column('generated_image_url', sa.String(length=450), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_requests', 'generated_image_url')
    op.drop_column('api_requests', 'status')
    # ### end Alembic commands ###
