"""init

Revision ID: 28b425bca213
Revises: 
Create Date: 2024-11-07 03:25:38.756834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b425bca213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_upscale_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_width', sa.Integer(), nullable=False),
    sa.Column('original_height', sa.Integer(), nullable=False),
    sa.Column('upscale_width', sa.Integer(), nullable=False),
    sa.Column('upscale_height', sa.Integer(), nullable=False),
    sa.Column('scale_factor', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('work_status', sa.String(length=50), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('api_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('original_width', sa.Integer(), nullable=False),
    sa.Column('original_height', sa.Integer(), nullable=False),
    sa.Column('upscale_width', sa.Integer(), nullable=False),
    sa.Column('upscale_height', sa.Integer(), nullable=False),
    sa.Column('scale_factor', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_requests')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('image_upscale_prices')
    # ### end Alembic commands ###
