"""api_requests task_id

Revision ID: 7464aa741f57
Revises: bd6b96da733c
Create Date: 2024-11-09 17:56:52.522015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7464aa741f57'
down_revision = 'bd6b96da733c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_requests', sa.Column('task_id', sa.String(length=250), nullable=True))
    op.drop_column('api_requests', 'upscale_width')
    op.drop_column('api_requests', 'upscale_height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_requests', sa.Column('upscale_height', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('api_requests', sa.Column('upscale_width', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('api_requests', 'task_id')
    # ### end Alembic commands ###
