"""Create default prices for image upscaling

Revision ID: bd6b96da733c
Revises: 28b425bca213
Create Date: 2024-11-09 11:50:16.815576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6b96da733c'
down_revision = '28b425bca213'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO image_upscale_prices (original_width, original_height, upscale_width, upscale_height, scale_factor, price) VALUES
        (640, 480, 1280, 960, '2x', 21.40),
        (640, 480, 2560, 1920, '4x', 85.60),
        (640, 480, 5120, 3840, '8x', 342.40),
        (1280, 720, 2560, 1440, '2x', 21.40),
        (1280, 720, 5120, 2880, '4x', 85.60),
        (1920, 1080, 3840, 2160, '2x', 42.80),
        (5000, 5000, 10000, 10000, '2x', 256.80);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM image_upscale_prices WHERE original_width IN (640, 1280, 1920, 5000) AND original_height IN (480, 720, 1080, 5000);
    """)
    # ### end Alembic commands ###